on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: b2f9bd4a7d60180f55a56f10c0b95812416e2434
        # ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=vmarinychev   
          -Dsonar.projectKey=cloudsonar1   
          -Dsonar.sources=.   
          -Dsonar.host.url=https://sonarcloud.io

      
