on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  #push:
  #  branches:
  #    - master
 # pull_request:
   #   types: [opened, synchronize, reopened]
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      project_Key:
        required: true
        type: string
    secrets:
      token_sonar: 
        required: true
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN:  ${{ secrets.token_sonar }}
        #${{ secrets.GITHUB_TOKEN }}
      with:
        args: >
          -Dsonar.organization=organization  
          -Dsonar.projectKey=project_Key  
          -Dsonar.sources=.   
          -Dsonar.host.url=https://sonarcloud.io

      
