on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN:  7b6b69e7436b38ea4e34e6a181b06dacfd87a128
        #${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=joshuamartel  
          -Dsonar.projectKey=ScalaSonarTest  
          -Dsonar.sources=.   
          -Dsonar.host.url=https://sonarcloud.io

      
